[profile.default]
src = "src"
out = "out"
solc = "0.8.30"
evm_version = "prague"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.2.0-rc.1"
solmate = "6.8.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
bsc-testnet = "${BSC_TESTNET_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
unichain-sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }