[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.2.0-rc.1"
solmate = "6.8.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
unichain-sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", chain = "sepolia", url = "https://api-sepolia.etherscan.io/api"}
base-sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}", chain = "base-sepolia", url = "https://api-sepolia.basescan.org/api" }
arbitrum-sepolia = { key = "${ARBITRUM_SEPOLIA_ETHERSCAN_API_KEY}", chain = "arbitrum-sepolia", url = "hhttps://api-sepolia.arbiscan.io/api" }
unichain-sepolia = { key = "${UNICHAIN_SEPOLIA_ETHERSCAN_API_KEY}", chain = "unichain-sepolia", url = "https://api-sepolia.uniscan.xyz/api" }